#!/usr/bin/env bash

export project=$(echo "$QUTE_URL" | sed -En 's@https://git[^/]+/[^/]+/([^/]+)/.*@\1@p')
export object=$(echo "$QUTE_URL" | sed -En 's@https://git[^/]+/[^/]+/[^/]+/.*[^[:xdigit:]]([[:xdigit:]]{40}).*@\1@p')

if [ -n "$project" ] && [ -n "$object" ]; then
  nvr --servername "/tmp/$project" --remote-send ":G fetch|G show $object<cr>"
fi
