#!/usr/bin/env bash

export project
export commit
export name
export pr
export file

hosting=$(echo "$QUTE_URL" | sed -En 's@https://([^/]+)/.*@\1@p')
project=$(echo "$QUTE_URL" | sed -En 's@https://[^/]+/([^/]+)/([^/]+)/.*@\U\1\/\U\2@p')

if [ -n "$project" ]; then
  case $hosting in
  github* )
    commit=$(echo "$QUTE_URL" | sed -En 's@https://[^/]+/.*/([[:xdigit:]]{40}).*@\1@p')
    ;;
  gitlab* )
    commit=$(echo "$QUTE_URL" | sed -En 's@https://[^/]+/.*commit_id=([[:xdigit:]]{40}).*@\1@p')
    ;;
  bitbucket* )
    commit=$(echo "$QUTE_URL" | sed -En 's@https://[^/]+/.*/commits/([[:xdigit:]]{40}).*@\1@p')
    ;;
  esac

  if [ -n "$commit" ]; then
    vim --servername "$project" --remote-send ":<c-u>G show $commit<cr>"
  else
    >&2 echo "No commit present in URL: $QUTE_URL"
    >&2 echo "  commit: $commit"
    exit 3
  fi
else
  >&2 echo "No project present in URL: $QUTE_URL"
  >&2 echo "  project: $project"
  exit 2
fi
