#!/usr/bin/env bash

export project
export object
export name

project=$(echo "$QUTE_URL" | sed -En 's@https://git[^/]+/([^/]+)/([^/]+)/.*@\U\1\/\U\2@p')

if [ -n "$project" ]; then
  object=$(echo "$QUTE_URL" | sed -En 's@https://git[^/]+/.*/([[:xdigit:]]{40}).*@\1@p')
  pr=$(echo "$QUTE_URL" | sed -En 's@https://git[^/]+/.*/pull/([[:digit:]]+)@\1@p')

  if [ -n "$object" ]; then
    vim --servername "$project" --remote-send ":<c-u>G show $object<cr>"
  elif [ -n "$pr" ]; then
    vim --servername "$project" --remote-send ":<c-u>G checkout <c-r>=trim(system('gh pr view --json headRefName --jq \"\\\"\\(.headRefName)\\\"\" $pr'))<cr>"
  else
    >&2 echo "No object present in URL: $QUTE_URL"
    >&2 echo "  object: $object"
    >&2 echo "  pr: $pr"
    exit 3
  fi
else
  >&2 echo "No project present in URL: $QUTE_URL"
  >&2 echo "  project: $project"
  exit 2
fi
