#!/usr/bin/env bash

current_branch=$(git branch --show-current)
export current_branch

main_branch=$(echo $(git symbolic-ref refs/remotes/origin/HEAD 2>/dev/null || echo master) | sed 's@^refs/remotes/origin/@@')
export main_branch

current_branch_origin=$(git merge-base "$main_branch" "$current_branch")
export current_branch_origin

git rebase --interactive "$(git merge-base @ @{u})"

function show_help {
  >&2 echo "Usage: git utls [changes|root|remove|rebase|wip]"
}

function rebase {
  >&2 echo "git utls: rebasing to $current_branch_origin…"
  git rebase --interactive "$current_branch_origin"
}

function remove_file {
  >&2 echo "git utls: removing $1 from history…"
  git filter-branch --prune-empty --tree-filter "rm -f $1" "$current_branch_origin..$current_branch"
}

function branch_origin {
  printf "$current_branch_origin"
}

case "$1" in
  remove)  remove_file ;;
  rebase)  rebase ;;
  *)       show_help ;;
esac
