#!/usr/bin/env bash

current_branch=$(git branch --show-current)
export current_branch

main_branch=$(echo $(git symbolic-ref refs/remotes/origin/HEAD 2>/dev/null || echo master) | sed 's@^refs/remotes/origin/@@')
export main_branch

current_branch_origin=$(git merge-base "$main_branch" "$current_branch")
export current_branch_origin

function show_help {
  >&2 echo "Usage: git utls [changes|root|remove|rebase|wip]"
}

function rebase {
  >&2 echo "git utls: rebasing to $current_branch_origin…"
  git rebase --interactive "$current_branch_origin"
}

function remove_file {
  >&2 echo "git utls: removing $1 from history…"
  git filter-branch --prune-empty --tree-filter "rm -f $1" "$current_branch_origin..$current_branch"
}

function root {
  git rev-parse --show-toplevel
}

function wip {
  git commit --no-verify -m "wip: $(curl -Ls whatthecommit.com/index.txt)"
}

function changes {
  git log --pretty=oneline $current_branch_origin..
}

case "$1" in
  changes) changes ;;
  root)    root ;;
  remove)  remove_file ;;
  rebase)  rebase ;;
  wip)     wip ;;
  *)       show_help ;;
esac
